pipeline {
  agent any
  options {
    skipDefaultCheckout()
  }
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Install Dependencies') {
      steps {
        dir('client') {
          sh 'npm install'
        }
      }
    }
    stage('Lint') {
      steps {
        dir('client') {
          sh 'npm run lint'
        }
      }
    }
    stage('Test') {
      steps {
        dir('client') {
          sh 'npm test'
        }
      }
    }
    stage('Build') {
      steps {
        dir('client') {
          sh 'npm run build'
        }
      }
    }
    stage('Deploy') {
      when {
        branch 'master'
      }
      steps {
        dir('client') {
          sh "cp -r dist /foodapp/client"
        }
      }
    }
  }
}