pipeline {
  agent any
  options {
    skipDefaultCheckout()
  }
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Build') {
      steps {
        dir('server') {
          sh 'docker built . -t food-app-server'
        }
      }
    }
    stage('Deploy') {
      when {
        branch 'master'
      }
      steps {
        dir('server') {
          sh "cp docker-compose.yml /food-app/server/docker-compose.yml"
          sh "docker-compose -f /food-app/server/docker-compose.yml down"
          sh "docker-compose -f /food-app/server/docker-compose.yml up -d"
        }
      }
    }
  }
}