apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: food-app
spec:
  rules:
    - host: pantry-api.paul-steele.com
      http:
        paths:
          - backend:
              serviceName: food-app
              servicePort: 80
            path: /
    - host: pantry.paul-steele.com
      http:
        paths:
          - backend:
              serviceName: food-app
              servicePort: 4000
  tls:
    - secretName: paul-steele.com
      hosts:
        - pantry-api.paul-steele.com
        - pantry.paul-steele.com
---
apiVersion: v1
kind: Service
metadata:
  name: food-app
spec:
  selector:
    app: food-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-app
  labels:
    app: food-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-app
  template:
    metadata:
      labels:
        app: food-app
    spec:
      containers:
        - name: food-app-server
          image: registry.paul-steele.com/food-app-server:latest
          ports:
            - name: food-app-server
              containerPort: 4000
        - name: food-app-client
          image: registry.paul-steele.com/food-app-client:latest
          ports:
            - name: food-app-client
              containerPort: 80
      imagePullSecrets:
        - name: registry.paul-steele.com
